server:
  port: 9100
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  file: logs/app.log
lombok:
  log:
    xslf4j:
      flagUsage: warning